package form;

import Console.Gioco;
import Console.Nintendo;
import Console.PC;
import Console.PS4;
import Console.Xbox;
import dbconnection.DbConnection;
import java.awt.Color;
import java.awt.Frame;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.SwingConstants;

/**
 *
 * @author Andrea Luiu, Alekos Coalbu, Fadda Antonio Giuseppe
 */
public class Guiainframe extends javax.swing.JFrame {

    public static String scelta;
    static int y = 30;
    JLabel background;
    JButton btn;
    DbConnection db = new DbConnection();
    List<JButton> btnList = new ArrayList<>();

    /**
     * Creates new form Guiainframe
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passwordJpanel = new javax.swing.JPanel();
        passwordField = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();
        userNameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        addJDialog = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        titoloTxt = new javax.swing.JTextField();
        piattaTxt = new javax.swing.JTextField();
        genereTxt = new javax.swing.JTextField();
        quantitaTxt = new javax.swing.JTextField();
        dataDiUscitaTxt = new javax.swing.JTextField();
        etaTxt = new javax.swing.JTextField();
        prezzoJtxt = new javax.swing.JTextField();
        addPaneljbt = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        descrizioneTxtArea = new javax.swing.JTextArea();
        backJbt = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        modJDialog = new javax.swing.JDialog();
        jLabel21 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        titoloTxtMod = new javax.swing.JTextField();
        prezzoJtxtMod = new javax.swing.JTextField();
        modPaneljbt = new javax.swing.JButton();
        backJbt2 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        nintendoJbt = new javax.swing.JButton();
        xboxJbt = new javax.swing.JButton();
        pcJbt = new javax.swing.JButton();
        ps4Jbt = new javax.swing.JButton();
        cercaJbt = new javax.swing.JButton();
        cercaTxt = new javax.swing.JTextField();
        addJbt = new javax.swing.JButton();
        modJbt = new javax.swing.JButton();

        passwordJpanel.setRequestFocusEnabled(false);
        passwordJpanel.setVerifyInputWhenFocusTarget(false);
        passwordJpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passwordField.setText("jPasswordField1");
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        passwordJpanel.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 160, -1));

        loginBtn.setText("Login ");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        passwordJpanel.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 80, 40));

        userNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameFieldActionPerformed(evt);
            }
        });
        passwordJpanel.add(userNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 157, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");
        passwordJpanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        passwordJpanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sfonfopass.jpg"))); // NOI18N
        passwordJpanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 360));

        addJDialog.setResizable(false);
        addJDialog.setSize(new java.awt.Dimension(500, 460));
        addJDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Titolo");
        addJDialog.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 37, -1));

        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Piattaforma");
        addJDialog.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 65, -1));

        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Genere");
        addJDialog.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 47, -1));

        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("      Età");
        addJDialog.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 47, -1));

        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Data di uscita");
        addJDialog.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 142, -1, -1));

        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Descrizione");
        addJDialog.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jLabel12.setForeground(new java.awt.Color(240, 240, 240));
        jLabel12.setText("Prezzo");
        addJDialog.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel11.setForeground(new java.awt.Color(240, 240, 240));
        jLabel11.setText("Quantità");
        addJDialog.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, 20));

        titoloTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titoloTxtActionPerformed(evt);
            }
        });
        addJDialog.getContentPane().add(titoloTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 310, -1));

        piattaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piattaTxtActionPerformed(evt);
            }
        });
        addJDialog.getContentPane().add(piattaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 310, -1));

        genereTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genereTxtActionPerformed(evt);
            }
        });
        addJDialog.getContentPane().add(genereTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 310, -1));
        addJDialog.getContentPane().add(quantitaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 310, -1));

        dataDiUscitaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataDiUscitaTxtActionPerformed(evt);
            }
        });
        addJDialog.getContentPane().add(dataDiUscitaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 310, -1));

        etaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etaTxtActionPerformed(evt);
            }
        });
        addJDialog.getContentPane().add(etaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 310, -1));
        addJDialog.getContentPane().add(prezzoJtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 310, -1));

        addPaneljbt.setText("Aggiungi");
        addPaneljbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPaneljbtActionPerformed(evt);
            }
        });
        addJDialog.getContentPane().add(addPaneljbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, -1, -1));

        descrizioneTxtArea.setColumns(20);
        descrizioneTxtArea.setRows(5);
        jScrollPane2.setViewportView(descrizioneTxtArea);

        addJDialog.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 310, 131));

        backJbt.setText("Indietro");
        backJbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJbtActionPerformed(evt);
            }
        });
        addJDialog.getContentPane().add(backJbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/razer1920x1200.jpg"))); // NOI18N
        addJDialog.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 460));

        modJDialog.setResizable(false);
        modJDialog.setSize(new java.awt.Dimension(500, 300));
        modJDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setForeground(new java.awt.Color(240, 240, 240));
        jLabel21.setText("Titolo");
        modJDialog.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 37, -1));

        jLabel27.setForeground(new java.awt.Color(240, 240, 240));
        jLabel27.setText("Prezzo");
        modJDialog.getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        titoloTxtMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titoloTxtModActionPerformed(evt);
            }
        });
        modJDialog.getContentPane().add(titoloTxtMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 310, -1));
        modJDialog.getContentPane().add(prezzoJtxtMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 310, -1));

        modPaneljbt.setText("Modifica");
        modPaneljbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modPaneljbtActionPerformed(evt);
            }
        });
        modJDialog.getContentPane().add(modPaneljbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        backJbt2.setText("Indietro");
        backJbt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJbt2ActionPerformed(evt);
            }
        });
        modJDialog.getContentPane().add(backJbt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/razer1920x1200.jpg"))); // NOI18N
        modJDialog.getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 460));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        nintendoJbt.setBackground(new java.awt.Color(0, 0, 0));
        nintendoJbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/nintendo.png"))); // NOI18N
        nintendoJbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nintendoJbtActionPerformed(evt);
            }
        });

        xboxJbt.setBackground(new java.awt.Color(0, 0, 0));
        xboxJbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/xbox.png"))); // NOI18N
        xboxJbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xboxJbtActionPerformed(evt);
            }
        });

        pcJbt.setBackground(new java.awt.Color(0, 0, 0));
        pcJbt.setForeground(new java.awt.Color(51, 51, 51));
        pcJbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/computer.png"))); // NOI18N
        pcJbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcJbtActionPerformed(evt);
            }
        });

        ps4Jbt.setBackground(new java.awt.Color(0, 0, 0));
        ps4Jbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/playstation.png"))); // NOI18N
        ps4Jbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ps4JbtActionPerformed(evt);
            }
        });

        cercaJbt.setBackground(new java.awt.Color(0, 0, 0));
        cercaJbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cerca.png"))); // NOI18N
        cercaJbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cercaJbtActionPerformed(evt);
            }
        });

        cercaTxt.setBackground(new java.awt.Color(51, 51, 51));
        cercaTxt.setFont(new java.awt.Font("Candara", 3, 12)); // NOI18N
        cercaTxt.setForeground(new java.awt.Color(240, 240, 240));
        cercaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cercaTxtActionPerformed(evt);
            }
        });

        addJbt.setBackground(new java.awt.Color(0, 0, 0));
        addJbt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addJbt.setForeground(new java.awt.Color(240, 240, 240));
        addJbt.setText("Aggiungi");
        addJbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJbtActionPerformed(evt);
            }
        });

        modJbt.setBackground(new java.awt.Color(0, 0, 0));
        modJbt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        modJbt.setForeground(new java.awt.Color(240, 240, 240));
        modJbt.setText("Modifica");
        modJbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modJbtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(addJbt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(modJbt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(pcJbt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(ps4Jbt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(nintendoJbt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(xboxJbt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cercaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cercaJbt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addJbt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modJbt))
                    .addComponent(cercaJbt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cercaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(nintendoJbt)
                .addGap(11, 11, 11)
                .addComponent(xboxJbt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(pcJbt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ps4Jbt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public Guiainframe() {
        initComponents();
        this.setResizable(false);
        this.setSize(580, 420);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        ImageIcon img = (new javax.swing.ImageIcon(getClass().getResource("/Images/Background.png")));
        background = new JLabel("", img, JLabel.CENTER);
        background.setBounds(0, 0, 1600, 600);
        this.add(background);

    }


    private void cercaJbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cercaJbtActionPerformed
            db.listGiochi.clear();
            btnList.clear();

        try {
            db.select2(cercaTxt.getText(), scelta);

            for (Gioco i : db.listGiochi) {
                y += 50;
                System.out.println(y);

                btn = new JButton(new javax.swing.ImageIcon(getClass().getResource("/Images/prova.png")));
                btn.setText("           " + i.getNome() + "                "
                        + "                   " + i.getPrezzo() + "     €");
                btn.setSize(400, 50);
                btn.setLocation(105, y);
                btn.setBackground(Color.black);
                btn.setForeground(Color.orange);
                btn.setHorizontalAlignment(SwingConstants.LEFT);
                background.add(btn);
                btnList.add(btn);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Guiainframe.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_cercaJbtActionPerformed

    private void nintendoJbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nintendoJbtActionPerformed
        scelta = "nintendo";

    }//GEN-LAST:event_nintendoJbtActionPerformed

    private void xboxJbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xboxJbtActionPerformed
        scelta = "xbox";
    }//GEN-LAST:event_xboxJbtActionPerformed

    private void pcJbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcJbtActionPerformed
        scelta = "pc";
    }//GEN-LAST:event_pcJbtActionPerformed

    private void ps4JbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ps4JbtActionPerformed
        scelta = "ps4";
    }//GEN-LAST:event_ps4JbtActionPerformed

    private void userNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameFieldActionPerformed
        //PER DATABASE
    }//GEN-LAST:event_userNameFieldActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtnActionPerformed

    private void cercaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cercaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cercaTxtActionPerformed

    private void addJbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJbtActionPerformed
        addJDialog.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_addJbtActionPerformed

    private void modJbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modJbtActionPerformed
        modJDialog.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_modJbtActionPerformed

    private void titoloTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titoloTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titoloTxtActionPerformed

    private void addPaneljbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPaneljbtActionPerformed
        try {
            db.insertGame(genereTxt.getText(), piattaTxt.getText(), Integer.parseInt(etaTxt.getText()),
                    descrizioneTxtArea.getText(), dataDiUscitaTxt.getText(), Integer.parseInt(quantitaTxt.getText()),
                    titoloTxt.getText(), Double.valueOf(prezzoJtxt.getText()));
        } catch (SQLException ex) {
            Logger.getLogger(Guiainframe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addPaneljbtActionPerformed

    private void backJbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJbtActionPerformed
        addJDialog.setVisible(false);
        this.setVisible(true);

    }//GEN-LAST:event_backJbtActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void piattaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piattaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_piattaTxtActionPerformed

    private void genereTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genereTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genereTxtActionPerformed

    private void etaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etaTxtActionPerformed

    private void dataDiUscitaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataDiUscitaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataDiUscitaTxtActionPerformed

    private void backJbt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJbt2ActionPerformed
        modJDialog.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_backJbt2ActionPerformed

    private void modPaneljbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modPaneljbtActionPerformed
        
            try {
                db.update(y, titoloTxtMod.getText(), Double.valueOf(prezzoJtxtMod.getText()));
            } catch (SQLException ex) {
                Logger.getLogger(Guiainframe.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_modPaneljbtActionPerformed

    private void titoloTxtModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titoloTxtModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titoloTxtModActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Guiainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Guiainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Guiainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Guiainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Guiainframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog addJDialog;
    private javax.swing.JButton addJbt;
    private javax.swing.JButton addPaneljbt;
    private javax.swing.JButton backJbt;
    private javax.swing.JButton backJbt2;
    private javax.swing.JButton cercaJbt;
    private javax.swing.JTextField cercaTxt;
    private javax.swing.JTextField dataDiUscitaTxt;
    private javax.swing.JTextArea descrizioneTxtArea;
    private javax.swing.JTextField etaTxt;
    private javax.swing.JTextField genereTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton loginBtn;
    private javax.swing.JDialog modJDialog;
    private javax.swing.JButton modJbt;
    private javax.swing.JButton modPaneljbt;
    private javax.swing.JButton nintendoJbt;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JPanel passwordJpanel;
    private javax.swing.JButton pcJbt;
    private javax.swing.JTextField piattaTxt;
    private javax.swing.JTextField prezzoJtxt;
    private javax.swing.JTextField prezzoJtxtMod;
    private javax.swing.JButton ps4Jbt;
    private javax.swing.JTextField quantitaTxt;
    private javax.swing.JTextField titoloTxt;
    private javax.swing.JTextField titoloTxtMod;
    private javax.swing.JTextField userNameField;
    private javax.swing.JButton xboxJbt;
    // End of variables declaration//GEN-END:variables

}
