package form;

import Console.Gioco;
import Console.Nintendo;
import Console.PC;
import Console.PS4;
import Console.Xbox;
import Login.Users;
import dbconnection.DbConnection;
import java.awt.Color;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.plaf.OptionPaneUI;

/**
 *
 * @author Andrea Luiu, Alekos Coalbu, Fadda Antonio Giuseppe
 */
public class Guiainframe extends javax.swing.JFrame {

    public static String scelta;
    static int y = 5;
    JLabel background;
    Users admin = new Users();
    JButton btn;
    String tipo;
    
    DbConnection db = new DbConnection();
    List<JButton> btnList = new ArrayList<>();
    final String DATA="admin";

    /**
     * Creates new form Guiainframe
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addJDialog = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        titoloTxt = new javax.swing.JTextField();
        piattaTxt = new javax.swing.JTextField();
        genereTxt = new javax.swing.JTextField();
        quantitaTxt = new javax.swing.JTextField();
        dataDiUscitaTxt = new javax.swing.JTextField();
        etaTxt = new javax.swing.JTextField();
        prezzoJtxt = new javax.swing.JTextField();
        addPaneljbt = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        descrizioneTxtArea = new javax.swing.JTextArea();
        backJbt = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        modJDialog = new javax.swing.JDialog();
        jLabel21 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        idTxtMod = new javax.swing.JTextField();
        titoloTxtMod = new javax.swing.JTextField();
        prezzoJtxtMod = new javax.swing.JTextField();
        modPaneljbt = new javax.swing.JButton();
        backJbt2 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        singjDialog = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        passwordSingTxt = new javax.swing.JPasswordField();
        userNameSingTxt = new javax.swing.JTextField();
        passBackjbt = new javax.swing.JButton();
        loginBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        deleteJDialog = new javax.swing.JDialog();
        idTxtDelete = new javax.swing.JTextField();
        deleteJBtDelete = new javax.swing.JButton();
        backJbtDelete = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        nintendoJbt = new javax.swing.JButton();
        xboxJbt = new javax.swing.JButton();
        pcJbt = new javax.swing.JButton();
        ps4Jbt = new javax.swing.JButton();
        cercaJbt = new javax.swing.JButton();
        addJbt = new javax.swing.JButton();
        modJbt = new javax.swing.JButton();
        loginJbtMain = new javax.swing.JButton();
        deleteJbt = new javax.swing.JButton();
        jpPannel = new javax.swing.JPanel();
        cercaTxt = new javax.swing.JTextField();

        addJDialog.setResizable(false);
        addJDialog.setSize(new java.awt.Dimension(550, 500));
        addJDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Titolo");
        addJDialog.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 37, 20));

        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Piattaforma");
        addJDialog.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 65, 20));

        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Genere");
        addJDialog.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 47, 20));

        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("      Età");
        addJDialog.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 40, 20));

        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("Data di uscita");
        addJDialog.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 80, 20));

        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Descrizione");
        addJDialog.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jLabel12.setForeground(new java.awt.Color(240, 240, 240));
        jLabel12.setText("Prezzo");
        addJDialog.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, 20));

        jLabel11.setForeground(new java.awt.Color(240, 240, 240));
        jLabel11.setText("Quantità");
        addJDialog.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 50, 20));

        titoloTxt.setBackground(new java.awt.Color(102, 102, 102));
        titoloTxt.setForeground(new java.awt.Color(204, 153, 0));
        titoloTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titoloTxtActionPerformed(evt);
            }
        });
        addJDialog.getContentPane().add(titoloTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 310, -1));

        piattaTxt.setBackground(new java.awt.Color(102, 102, 102));
        piattaTxt.setForeground(new java.awt.Color(204, 153, 0));
        piattaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piattaTxtActionPerformed(evt);
            }
        });
        addJDialog.getContentPane().add(piattaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 310, -1));

        genereTxt.setBackground(new java.awt.Color(102, 102, 102));
        genereTxt.setForeground(new java.awt.Color(204, 153, 0));
        genereTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genereTxtActionPerformed(evt);
            }
        });
        addJDialog.getContentPane().add(genereTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 310, -1));

        quantitaTxt.setBackground(new java.awt.Color(102, 102, 102));
        quantitaTxt.setForeground(new java.awt.Color(204, 153, 0));
        addJDialog.getContentPane().add(quantitaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 310, -1));

        dataDiUscitaTxt.setBackground(new java.awt.Color(102, 102, 102));
        dataDiUscitaTxt.setForeground(new java.awt.Color(204, 153, 0));
        dataDiUscitaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataDiUscitaTxtActionPerformed(evt);
            }
        });
        addJDialog.getContentPane().add(dataDiUscitaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 310, -1));

        etaTxt.setBackground(new java.awt.Color(102, 102, 102));
        etaTxt.setForeground(new java.awt.Color(204, 153, 0));
        etaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etaTxtActionPerformed(evt);
            }
        });
        addJDialog.getContentPane().add(etaTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 310, -1));

        prezzoJtxt.setBackground(new java.awt.Color(102, 102, 102));
        prezzoJtxt.setForeground(new java.awt.Color(204, 153, 0));
        addJDialog.getContentPane().add(prezzoJtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 310, -1));

        addPaneljbt.setBackground(new java.awt.Color(0, 0, 0));
        addPaneljbt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addPaneljbt.setForeground(new java.awt.Color(204, 153, 0));
        addPaneljbt.setText("Aggiungi");
        addPaneljbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPaneljbtActionPerformed(evt);
            }
        });
        addJDialog.getContentPane().add(addPaneljbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, -1, -1));

        descrizioneTxtArea.setBackground(new java.awt.Color(102, 102, 102));
        descrizioneTxtArea.setColumns(20);
        descrizioneTxtArea.setForeground(new java.awt.Color(255, 153, 0));
        descrizioneTxtArea.setRows(5);
        jScrollPane2.setViewportView(descrizioneTxtArea);

        addJDialog.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 310, 131));

        backJbt.setBackground(new java.awt.Color(0, 0, 0));
        backJbt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        backJbt.setForeground(new java.awt.Color(204, 153, 0));
        backJbt.setText("Indietro");
        backJbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJbtActionPerformed(evt);
            }
        });
        addJDialog.getContentPane().add(backJbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wallpaperflare.com_wallpaper.jpg"))); // NOI18N
        addJDialog.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 500));

        modJDialog.setResizable(false);
        modJDialog.setSize(new java.awt.Dimension(500, 300));
        modJDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setForeground(new java.awt.Color(240, 240, 240));
        jLabel21.setText("Titolo");
        modJDialog.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 37, 20));

        jLabel27.setForeground(new java.awt.Color(240, 240, 240));
        jLabel27.setText("Prezzo");
        modJDialog.getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, 20));

        jLabel13.setForeground(new java.awt.Color(240, 240, 240));
        jLabel13.setText("ID Game");
        modJDialog.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 20));

        idTxtMod.setBackground(new java.awt.Color(102, 102, 102));
        modJDialog.getContentPane().add(idTxtMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 310, -1));

        titoloTxtMod.setBackground(new java.awt.Color(102, 102, 102));
        titoloTxtMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titoloTxtModActionPerformed(evt);
            }
        });
        modJDialog.getContentPane().add(titoloTxtMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 310, -1));

        prezzoJtxtMod.setBackground(new java.awt.Color(102, 102, 102));
        modJDialog.getContentPane().add(prezzoJtxtMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 310, -1));

        modPaneljbt.setBackground(new java.awt.Color(0, 0, 0));
        modPaneljbt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        modPaneljbt.setForeground(new java.awt.Color(255, 153, 0));
        modPaneljbt.setText("Modifica");
        modPaneljbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modPaneljbtActionPerformed(evt);
            }
        });
        modJDialog.getContentPane().add(modPaneljbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        backJbt2.setBackground(new java.awt.Color(0, 0, 0));
        backJbt2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        backJbt2.setForeground(new java.awt.Color(255, 153, 0));
        backJbt2.setText("Indietro");
        backJbt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJbt2ActionPerformed(evt);
            }
        });
        modJDialog.getContentPane().add(backJbt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/wallpaperflare.com_wallpaper.jpg"))); // NOI18N
        modJDialog.getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 460));

        singjDialog.setResizable(false);
        singjDialog.setSize(new java.awt.Dimension(500, 400));
        singjDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        singjDialog.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");
        singjDialog.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        passwordSingTxt.setText("jPasswordField1");
        passwordSingTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordSingTxtActionPerformed(evt);
            }
        });
        singjDialog.getContentPane().add(passwordSingTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 160, -1));

        userNameSingTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameSingTxtActionPerformed(evt);
            }
        });
        singjDialog.getContentPane().add(userNameSingTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 160, -1));

        passBackjbt.setBackground(new java.awt.Color(0, 102, 102));
        passBackjbt.setForeground(new java.awt.Color(255, 255, 255));
        passBackjbt.setText("Indietro");
        passBackjbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passBackjbtActionPerformed(evt);
            }
        });
        singjDialog.getContentPane().add(passBackjbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 70, 20));

        loginBtn.setBackground(new java.awt.Color(0, 102, 102));
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("Login ");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        singjDialog.getContentPane().add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 70, 20));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/black-and-white-3d-wallpaper_1920x1080.jpg"))); // NOI18N
        singjDialog.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 400));

        deleteJDialog.setResizable(false);
        deleteJDialog.setSize(new java.awt.Dimension(260, 190));
        deleteJDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idTxtDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTxtDeleteActionPerformed(evt);
            }
        });
        deleteJDialog.getContentPane().add(idTxtDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 150, -1));

        deleteJBtDelete.setText("Elimina");
        deleteJBtDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteJBtDeleteActionPerformed(evt);
            }
        });
        deleteJDialog.getContentPane().add(deleteJBtDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        backJbtDelete.setText("Indietro");
        backJbtDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJbtDeleteActionPerformed(evt);
            }
        });
        deleteJDialog.getContentPane().add(backJbtDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("ID");
        deleteJDialog.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 30, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gameover.png"))); // NOI18N
        deleteJDialog.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 150));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        nintendoJbt.setBackground(new java.awt.Color(0, 0, 0));
        nintendoJbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/nintendo.png"))); // NOI18N
        nintendoJbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nintendoJbtActionPerformed(evt);
            }
        });

        xboxJbt.setBackground(new java.awt.Color(0, 0, 0));
        xboxJbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/xbox.png"))); // NOI18N
        xboxJbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xboxJbtActionPerformed(evt);
            }
        });

        pcJbt.setBackground(new java.awt.Color(0, 0, 0));
        pcJbt.setForeground(new java.awt.Color(51, 51, 51));
        pcJbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/computer.png"))); // NOI18N
        pcJbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcJbtActionPerformed(evt);
            }
        });

        ps4Jbt.setBackground(new java.awt.Color(0, 0, 0));
        ps4Jbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/playstation.png"))); // NOI18N
        ps4Jbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ps4JbtActionPerformed(evt);
            }
        });

        cercaJbt.setBackground(new java.awt.Color(0, 0, 0));
        cercaJbt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cerca.png"))); // NOI18N
        cercaJbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cercaJbtActionPerformed(evt);
            }
        });

        addJbt.setBackground(new java.awt.Color(0, 0, 0));
        addJbt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addJbt.setForeground(new java.awt.Color(240, 240, 240));
        addJbt.setText("Aggiungi");
        addJbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJbtActionPerformed(evt);
            }
        });

        modJbt.setBackground(new java.awt.Color(0, 0, 0));
        modJbt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        modJbt.setForeground(new java.awt.Color(240, 240, 240));
        modJbt.setText("Modifica");
        modJbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modJbtActionPerformed(evt);
            }
        });

        loginJbtMain.setBackground(new java.awt.Color(0, 0, 0));
        loginJbtMain.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        loginJbtMain.setForeground(new java.awt.Color(240, 240, 240));
        loginJbtMain.setText("Login admin");
        loginJbtMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginJbtMainActionPerformed(evt);
            }
        });

        deleteJbt.setBackground(new java.awt.Color(0, 0, 0));
        deleteJbt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        deleteJbt.setForeground(new java.awt.Color(255, 255, 255));
        deleteJbt.setText("Delete");
        deleteJbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteJbtActionPerformed(evt);
            }
        });

        jpPannel.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jpPannelLayout = new javax.swing.GroupLayout(jpPannel);
        jpPannel.setLayout(jpPannelLayout);
        jpPannelLayout.setHorizontalGroup(
            jpPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );
        jpPannelLayout.setVerticalGroup(
            jpPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        cercaTxt.setBackground(new java.awt.Color(51, 51, 51));
        cercaTxt.setFont(new java.awt.Font("Candara", 3, 12)); // NOI18N
        cercaTxt.setForeground(new java.awt.Color(240, 240, 240));
        cercaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cercaTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ps4Jbt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nintendoJbt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xboxJbt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pcJbt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginJbtMain)
                    .addComponent(deleteJbt, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addJbt, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modJbt, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(cercaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cercaJbt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cercaJbt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cercaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpPannel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(loginJbtMain, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteJbt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addJbt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modJbt)
                        .addGap(18, 18, 18)
                        .addComponent(nintendoJbt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(xboxJbt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(pcJbt)
                        .addGap(11, 11, 11)
                        .addComponent(ps4Jbt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 163, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public Guiainframe() {
        initComponents();
        this.setResizable(false);
        this.setSize(580, 420);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        tipo = "user";       
        ImageIcon img = (new
          javax.swing.ImageIcon(getClass().getResource("/Images/wallpaperflare.com_wallpaper.jpg")));
         background = new JLabel("", img, JLabel.CENTER);
          background.setBounds(0, 0, 1366, 768);
        this.add(background);
        if (tipo.equals("user")) {
            addJbt.setVisible(false);
            modJbt.setVisible(false);
            deleteJbt.setVisible(false);
        }
       
          
        jpPannel.setOpaque(false);
    }


    private void cercaJbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cercaJbtActionPerformed
        jpPannel.removeAll();
        jpPannel.revalidate();
        jpPannel.repaint();
        y=5;
        try {
            //btnList.forEach(e -> e.);
              db.listGiochi.clear();
            System.out.println(btnList.size() + " size");
            btnList.clear();
            
            String scelta1=db.select2(cercaTxt.getText(), scelta);
            if (!scelta1.equals(scelta)){
                JOptionPane.showMessageDialog(this,"Piattaforma non selezionata\n e/o \ngioco non trovato");
                System.out.println("__"+scelta1+"__scelta__"+scelta+"__");
                return;
            }
            for (Gioco i : db.listGiochi) {
             

                System.out.println(y);
                JButton jbtn = new JButton(new javax.swing.ImageIcon(getClass().getResource("/Images/video-game.png")));
                jbtn.setText("           " + i.getNome() + "                "
                        + "                   " + i.getPrezzo() + "     €");
                jbtn.setSize(400, 50);
                jbtn.setLocation(10, y);
                jbtn.setBackground(Color.black);
                jbtn.setForeground(Color.orange);
                jbtn.setHorizontalAlignment(SwingConstants.LEFT);
                btnList.add(jbtn);
                   y += 50;
                jbtn.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        JOptionPane.showMessageDialog(jbtn, "Titolo\n" + i.getNome() + "\nPiattaforma\n"
                                + i.getPiattaforma() + "\nGenere\n"
                                + i.getGenere() + "\nPEGI\n"
                                + i.getAge() + "\nData di uscita\n"
                                + i.getDataUscita() + "\nPrezzo\n"
                                + i.getPrezzo() + "\nDescrizione\n"
                                + i.getDescrizione() + "\n");

                    }
                });
               
            }

            btnList.forEach(e -> jpPannel.add(e));

          

        } catch (Exception ex) {
           JOptionPane.showMessageDialog(this,"Piattaforma non selezionata\n e/o \ngioco non trovato");
        }


    }//GEN-LAST:event_cercaJbtActionPerformed

    private void nintendoJbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nintendoJbtActionPerformed
        scelta = "nintendo";

    }//GEN-LAST:event_nintendoJbtActionPerformed

    private void xboxJbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xboxJbtActionPerformed
        scelta = "xbox";
    }//GEN-LAST:event_xboxJbtActionPerformed

    private void pcJbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcJbtActionPerformed
        scelta = "pc";
    }//GEN-LAST:event_pcJbtActionPerformed

    private void ps4JbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ps4JbtActionPerformed
        scelta = "ps4";
    }//GEN-LAST:event_ps4JbtActionPerformed

    private void cercaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cercaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cercaTxtActionPerformed

    private void addJbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJbtActionPerformed
        addJDialog.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_addJbtActionPerformed

    private void modJbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modJbtActionPerformed
        modJDialog.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_modJbtActionPerformed

    private void titoloTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titoloTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titoloTxtActionPerformed

    private void addPaneljbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPaneljbtActionPerformed
        try {
            db.insertGame(genereTxt.getText(), piattaTxt.getText(), Integer.parseInt(etaTxt.getText()),
                    descrizioneTxtArea.getText(), dataDiUscitaTxt.getText(), Integer.parseInt(quantitaTxt.getText()),
                    titoloTxt.getText(), Double.valueOf(prezzoJtxt.getText()));
        } catch (SQLException ex) {
            Logger.getLogger(Guiainframe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addPaneljbtActionPerformed

    private void backJbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJbtActionPerformed
        addJDialog.setVisible(false);
        this.setVisible(true);

    }//GEN-LAST:event_backJbtActionPerformed

    private void piattaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piattaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_piattaTxtActionPerformed

    private void genereTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genereTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genereTxtActionPerformed

    private void etaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etaTxtActionPerformed

    private void dataDiUscitaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataDiUscitaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataDiUscitaTxtActionPerformed

    private void backJbt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJbt2ActionPerformed
        modJDialog.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_backJbt2ActionPerformed

    private void modPaneljbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modPaneljbtActionPerformed
   
        try {
            
            db.update(Integer.parseInt(idTxtMod.getText()), titoloTxtMod.getText(), Double.valueOf(prezzoJtxtMod.getText()));
        modJDialog.setVisible(false);
        this.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "inserire parametri correti per la ricerca del gioco");
        }

    }//GEN-LAST:event_modPaneljbtActionPerformed

    private void titoloTxtModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titoloTxtModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titoloTxtModActionPerformed

    private void loginJbtMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginJbtMainActionPerformed
        singjDialog.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_loginJbtMainActionPerformed

    @SuppressWarnings("deprecation")
    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed

        try {
            String []ar= db.selectUser().split(",");
            admin.setUsername(userNameSingTxt.getText());
            admin.setPassword(passwordSingTxt.getText());
            tipo = DATA;
            if (tipo.equals(DATA) && admin.getUsername().equals(DATA) && admin.getPassword().equals(DATA)) {
                addJbt.setVisible(true);
                modJbt.setVisible(true);
                singjDialog.setVisible(false);
                deleteJbt.setVisible(true);
                loginJbtMain.setVisible(false);
                this.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "username o/e password errata ");
            }

        } catch (SQLException ex) {
            Logger.getLogger(Guiainframe.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_loginBtnActionPerformed

    private void passBackjbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passBackjbtActionPerformed
        singjDialog.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_passBackjbtActionPerformed

    private void userNameSingTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameSingTxtActionPerformed
        //PER DATABASE
    }//GEN-LAST:event_userNameSingTxtActionPerformed

    private void passwordSingTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordSingTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordSingTxtActionPerformed

    private void deleteJbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteJbtActionPerformed
        deleteJDialog.setVisible(true);
        this.setVisible(false);
       // db.delete(deleteJbt);
       
    }//GEN-LAST:event_deleteJbtActionPerformed

    private void idTxtDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTxtDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTxtDeleteActionPerformed

    private void backJbtDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJbtDeleteActionPerformed
         deleteJDialog.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_backJbtDeleteActionPerformed

    private void deleteJBtDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteJBtDeleteActionPerformed
         
        try {
            db.delete(Integer.parseInt(idTxtDelete.getText()));
              deleteJDialog.setVisible(false);
              this.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "ID errato o non valido");
        }
      
    }//GEN-LAST:event_deleteJBtDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Guiainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Guiainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Guiainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Guiainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Guiainframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog addJDialog;
    private javax.swing.JButton addJbt;
    private javax.swing.JButton addPaneljbt;
    private javax.swing.JButton backJbt;
    private javax.swing.JButton backJbt2;
    private javax.swing.JButton backJbtDelete;
    private javax.swing.JButton cercaJbt;
    private javax.swing.JTextField cercaTxt;
    private javax.swing.JTextField dataDiUscitaTxt;
    private javax.swing.JButton deleteJBtDelete;
    private javax.swing.JDialog deleteJDialog;
    private javax.swing.JButton deleteJbt;
    private javax.swing.JTextArea descrizioneTxtArea;
    private javax.swing.JTextField etaTxt;
    private javax.swing.JTextField genereTxt;
    private javax.swing.JTextField idTxtDelete;
    private javax.swing.JTextField idTxtMod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpPannel;
    private javax.swing.JButton loginBtn;
    private javax.swing.JButton loginJbtMain;
    private javax.swing.JDialog modJDialog;
    private javax.swing.JButton modJbt;
    private javax.swing.JButton modPaneljbt;
    private javax.swing.JButton nintendoJbt;
    private javax.swing.JButton passBackjbt;
    private javax.swing.JPasswordField passwordSingTxt;
    private javax.swing.JButton pcJbt;
    private javax.swing.JTextField piattaTxt;
    private javax.swing.JTextField prezzoJtxt;
    private javax.swing.JTextField prezzoJtxtMod;
    private javax.swing.JButton ps4Jbt;
    private javax.swing.JTextField quantitaTxt;
    private javax.swing.JDialog singjDialog;
    private javax.swing.JTextField titoloTxt;
    private javax.swing.JTextField titoloTxtMod;
    private javax.swing.JTextField userNameSingTxt;
    private javax.swing.JButton xboxJbt;
    // End of variables declaration//GEN-END:variables

}
